/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthenticationEmailLoginRequestBody
 */
export interface AuthenticationEmailLoginRequestBody {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationEmailLoginRequestBody
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationEmailLoginRequestBody
     */
    'password': string;
}

