/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CatalogImageEntity
 */
export interface CatalogImageEntity {
    /**
     * 
     * @type {string}
     * @memberof CatalogImageEntity
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CatalogImageEntity
     */
    'squareId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CatalogImageEntity
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CatalogImageEntity
     */
    'url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CatalogImageEntity
     */
    'caption'?: string | null;
}

