/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CategoriesPatchBody
 */
export interface CategoriesPatchBody {
    /**
     * 
     * @type {string}
     * @memberof CategoriesPatchBody
     */
    'id': string;
    /**
     * 
     * @type {boolean}
     * @memberof CategoriesPatchBody
     */
    'moaEnabled'?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof CategoriesPatchBody
     */
    'moaOrdinal'?: number | null;
}

