/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FulfillmentRecipientInput
 */
export interface FulfillmentRecipientInput {
    /**
     * 
     * @type {string}
     * @memberof FulfillmentRecipientInput
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentRecipientInput
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentRecipientInput
     */
    'phoneNumber'?: string | null;
}

