/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AppConfigEntity } from './app-config-entity';
// May contain unused imports in some cases
// @ts-ignore
import { CatalogEntity } from './catalog-entity';
// May contain unused imports in some cases
// @ts-ignore
import { UserEntity } from './user-entity';

/**
 * 
 * @export
 * @interface MerchantEntity
 */
export interface MerchantEntity {
    /**
     * 
     * @type {AppConfigEntity}
     * @memberof MerchantEntity
     */
    'appConfig'?: AppConfigEntity | null;
    /**
     * 
     * @type {CatalogEntity}
     * @memberof MerchantEntity
     */
    'catalog'?: CatalogEntity | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantEntity
     */
    'id'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MerchantEntity
     */
    'pickupLeadDurationMinutes'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantEntity
     */
    'squareId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantEntity
     */
    'stripeId'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MerchantEntity
     */
    'tier'?: number | null;
    /**
     * 
     * @type {UserEntity}
     * @memberof MerchantEntity
     */
    'user'?: UserEntity | null;
}

