/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StatisticsOutput
 */
export interface StatisticsOutput {
    /**
     * 
     * @type {number}
     * @memberof StatisticsOutput
     */
    'average'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StatisticsOutput
     */
    'maximum'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StatisticsOutput
     */
    'minimum'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StatisticsOutput
     */
    'sum'?: number | null;
}

