/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SupportRequestPostBody
 */
export interface SupportRequestPostBody {
    /**
     * 
     * @type {string}
     * @memberof SupportRequestPostBody
     */
    'subject'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupportRequestPostBody
     */
    'text'?: string | null;
}

