/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Merchants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AppearanceEnum } from './appearance-enum';
// May contain unused imports in some cases
// @ts-ignore
import { ColorModeEnum } from './color-mode-enum';

/**
 * 
 * @export
 * @interface AppConfig
 */
export interface AppConfig {
    /**
     * 
     * @type {string}
     * @memberof AppConfig
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppConfig
     */
    'seedColor'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppConfig
     */
    'fontFamily'?: string;
    /**
     * 
     * @type {AppearanceEnum}
     * @memberof AppConfig
     */
    'appearance'?: AppearanceEnum;
    /**
     * 
     * @type {ColorModeEnum}
     * @memberof AppConfig
     */
    'colorMode'?: ColorModeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppConfig
     */
    'shortDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppConfig
     */
    'fullDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppConfig
     */
    'keywords'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppConfig
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppConfig
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppConfig
     */
    'blockingMessage'?: string;
}

