/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Merchants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import { BusinessHoursPeriod } from './business-hours-period';

/**
 * 
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    'moaOrdinal'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Location
     */
    'moaEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Location
     */
    'isMain': boolean;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'timezone'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'languageCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'currency'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'businessName'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'websiteUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'businessEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'twitterUsername'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'instagramUsername'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'facebookUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'logoUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'posBackgroundUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'mcc'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'fullFormatLogoUrl'?: string;
    /**
     * 
     * @type {Array<BusinessHoursPeriod>}
     * @memberof Location
     */
    'businessHours'?: Array<BusinessHoursPeriod>;
    /**
     * 
     * @type {Address}
     * @memberof Location
     */
    'address'?: Address;
}

