/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Merchants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LocationUpdateDto
 */
export interface LocationUpdateDto {
    /**
     * 
     * @type {number}
     * @memberof LocationUpdateDto
     */
    'moaOrdinal'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof LocationUpdateDto
     */
    'moaEnabled'?: boolean | null;
}

