/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Merchants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Modifier
 */
export interface Modifier {
    /**
     * 
     * @type {string}
     * @memberof Modifier
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Modifier
     */
    'name'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Modifier
     */
    'ordinal'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Modifier
     */
    'priceAmount'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Modifier
     */
    'priceCurrency'?: string | null;
}

