/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Merchants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { VariationAddDto } from './variation-add-dto';

/**
 * 
 * @export
 * @interface OrderCreateDto
 */
export interface OrderCreateDto {
    /**
     * 
     * @type {Array<VariationAddDto>}
     * @memberof OrderCreateDto
     */
    'variations'?: Array<VariationAddDto> | null;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateDto
     */
    'locationId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateDto
     */
    'idempotencyKey'?: string | null;
}

