/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Merchants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StripeCheckoutCreateDto
 */
export interface StripeCheckoutCreateDto {
    /**
     * 
     * @type {string}
     * @memberof StripeCheckoutCreateDto
     */
    'cancelUrl': string;
    /**
     * 
     * @type {string}
     * @memberof StripeCheckoutCreateDto
     */
    'stripePriceId': string;
    /**
     * 
     * @type {string}
     * @memberof StripeCheckoutCreateDto
     */
    'successUrl': string;
}

