/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Merchants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StripeBillingPortalCreateOutput
 */
export interface StripeBillingPortalCreateOutput {
    /**
     * 
     * @type {string}
     * @memberof StripeBillingPortalCreateOutput
     */
    'url': string;
}

