/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Merchants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Variation
 */
export interface Variation {
    /**
     * 
     * @type {string}
     * @memberof Variation
     */
    'id'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Variation
     */
    'ordinal'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Variation
     */
    'moaEnabled'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof Variation
     */
    'name'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Variation
     */
    'priceInCents'?: number | null;
}

