/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Merchants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CatalogImage } from '../moa-merchants-models';
// @ts-ignore
import { Category } from '../moa-merchants-models';
// @ts-ignore
import { CategoryPaginatedResponse } from '../moa-merchants-models';
// @ts-ignore
import { CategoryUpdateAllDto } from '../moa-merchants-models';
// @ts-ignore
import { CategoryUpdateDto } from '../moa-merchants-models';
// @ts-ignore
import { Item } from '../moa-merchants-models';
// @ts-ignore
import { ItemPaginatedResponse } from '../moa-merchants-models';
// @ts-ignore
import { ItemUpdateAllDto } from '../moa-merchants-models';
// @ts-ignore
import { ItemUpdateDto } from '../moa-merchants-models';
// @ts-ignore
import { NestError } from '../moa-merchants-models';
// @ts-ignore
import { Variation } from '../moa-merchants-models';
// @ts-ignore
import { VariationUpdateDto } from '../moa-merchants-models';
/**
 * CatalogsApi - axios parameter creator
 * @export
 */
export const CatalogsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Categories for Merchant ID with Items, Variations, and/or ModifierLists
         * @param {string} merchantId 
         * @param {GetCatalogActingAsEnum} actingAs 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {string} [locationId] 
         * @param {boolean} [items] 
         * @param {boolean} [images] 
         * @param {boolean} [variations] 
         * @param {boolean} [modifierLists] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCatalog: async (merchantId: string, actingAs: GetCatalogActingAsEnum, page?: number, limit?: number, locationId?: string, items?: boolean, images?: boolean, variations?: boolean, modifierLists?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'merchantId' is not null or undefined
            assertParamExists('getCatalog', 'merchantId', merchantId)
            // verify required parameter 'actingAs' is not null or undefined
            assertParamExists('getCatalog', 'actingAs', actingAs)
            const localVarPath = `/v2/catalog`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "Api-Key", configuration)

            if (merchantId !== undefined) {
                localVarQueryParameter['merchantId'] = merchantId;
            }

            if (actingAs !== undefined) {
                localVarQueryParameter['actingAs'] = actingAs;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (locationId !== undefined) {
                localVarQueryParameter['locationId'] = locationId;
            }

            if (items !== undefined) {
                localVarQueryParameter['items'] = items;
            }

            if (images !== undefined) {
                localVarQueryParameter['images'] = images;
            }

            if (variations !== undefined) {
                localVarQueryParameter['variations'] = variations;
            }

            if (modifierLists !== undefined) {
                localVarQueryParameter['modifierLists'] = modifierLists;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Item with ID
         * @param {string} id 
         * @param {string} [locationId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItem: async (id: string, locationId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getItem', 'id', id)
            const localVarPath = `/v2/items/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "Api-Key", configuration)

            if (locationId !== undefined) {
                localVarQueryParameter['locationId'] = locationId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Items in Category
         * @param {string} id 
         * @param {GetItemsInCategoryActingAsEnum} [actingAs] 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {string} [locationId] 
         * @param {boolean} [images] 
         * @param {boolean} [variations] 
         * @param {boolean} [modifierLists] 
         * @param {string} [merchantId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItemsInCategory: async (id: string, actingAs?: GetItemsInCategoryActingAsEnum, page?: number, limit?: number, locationId?: string, images?: boolean, variations?: boolean, modifierLists?: boolean, merchantId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getItemsInCategory', 'id', id)
            const localVarPath = `/v2/categories/{id}/items`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "Api-Key", configuration)

            if (actingAs !== undefined) {
                localVarQueryParameter['actingAs'] = actingAs;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (locationId !== undefined) {
                localVarQueryParameter['locationId'] = locationId;
            }

            if (images !== undefined) {
                localVarQueryParameter['images'] = images;
            }

            if (variations !== undefined) {
                localVarQueryParameter['variations'] = variations;
            }

            if (modifierLists !== undefined) {
                localVarQueryParameter['modifierLists'] = modifierLists;
            }

            if (merchantId !== undefined) {
                localVarQueryParameter['merchantId'] = merchantId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get your Categories with Items, Variations, and/or ModifierLists
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {string} [locationId] 
         * @param {boolean} [items] 
         * @param {boolean} [images] 
         * @param {boolean} [variations] 
         * @param {boolean} [modifierLists] 
         * @param {GetMyCatalogActingAsEnum} [actingAs] 
         * @param {string} [merchantId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCatalog: async (page?: number, limit?: number, locationId?: string, items?: boolean, images?: boolean, variations?: boolean, modifierLists?: boolean, actingAs?: GetMyCatalogActingAsEnum, merchantId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/catalog/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "Api-Key", configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (locationId !== undefined) {
                localVarQueryParameter['locationId'] = locationId;
            }

            if (items !== undefined) {
                localVarQueryParameter['items'] = items;
            }

            if (images !== undefined) {
                localVarQueryParameter['images'] = images;
            }

            if (variations !== undefined) {
                localVarQueryParameter['variations'] = variations;
            }

            if (modifierLists !== undefined) {
                localVarQueryParameter['modifierLists'] = modifierLists;
            }

            if (actingAs !== undefined) {
                localVarQueryParameter['actingAs'] = actingAs;
            }

            if (merchantId !== undefined) {
                localVarQueryParameter['merchantId'] = merchantId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Item variations with ID
         * @param {string} id 
         * @param {string} [locationId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVariationsForItem: async (id: string, locationId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getVariationsForItem', 'id', id)
            const localVarPath = `/v2/items/{id}/variations`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "Api-Key", configuration)

            if (locationId !== undefined) {
                localVarQueryParameter['locationId'] = locationId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update multiple Categories
         * @param {Array<CategoryUpdateAllDto>} categoryUpdateAllDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCategories: async (categoryUpdateAllDto: Array<CategoryUpdateAllDto>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'categoryUpdateAllDto' is not null or undefined
            assertParamExists('updateCategories', 'categoryUpdateAllDto', categoryUpdateAllDto)
            const localVarPath = `/v2/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "Api-Key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(categoryUpdateAllDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a Category
         * @param {string} id 
         * @param {CategoryUpdateDto} categoryUpdateDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCategory: async (id: string, categoryUpdateDto: CategoryUpdateDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateCategory', 'id', id)
            // verify required parameter 'categoryUpdateDto' is not null or undefined
            assertParamExists('updateCategory', 'categoryUpdateDto', categoryUpdateDto)
            const localVarPath = `/v2/categories/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "Api-Key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(categoryUpdateDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an Item
         * @param {string} id 
         * @param {ItemUpdateDto} itemUpdateDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateItem: async (id: string, itemUpdateDto: ItemUpdateDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateItem', 'id', id)
            // verify required parameter 'itemUpdateDto' is not null or undefined
            assertParamExists('updateItem', 'itemUpdateDto', itemUpdateDto)
            const localVarPath = `/v2/items/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "Api-Key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(itemUpdateDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update multiple Items
         * @param {Array<ItemUpdateAllDto>} itemUpdateAllDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateItems: async (itemUpdateAllDto: Array<ItemUpdateAllDto>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'itemUpdateAllDto' is not null or undefined
            assertParamExists('updateItems', 'itemUpdateAllDto', itemUpdateAllDto)
            const localVarPath = `/v2/items`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "Api-Key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(itemUpdateAllDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an Variation
         * @param {string} id 
         * @param {VariationUpdateDto} variationUpdateDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVariation: async (id: string, variationUpdateDto: VariationUpdateDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateVariation', 'id', id)
            // verify required parameter 'variationUpdateDto' is not null or undefined
            assertParamExists('updateVariation', 'variationUpdateDto', variationUpdateDto)
            const localVarPath = `/v2/variations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "Api-Key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(variationUpdateDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload Square Catalog Image
         * @param {string} idempotencyKey 
         * @param {string} id 
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadImageToSquareCatalog: async (idempotencyKey: string, id: string, file?: File, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('uploadImageToSquareCatalog', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('uploadImageToSquareCatalog', 'id', id)
            const localVarPath = `/v2/items/{id}/square/image`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication Api-Key required
            await setApiKeyToObject(localVarHeaderParameter, "Api-Key", configuration)

            if (idempotencyKey !== undefined) {
                localVarQueryParameter['idempotencyKey'] = idempotencyKey;
            }


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CatalogsApi - functional programming interface
 * @export
 */
export const CatalogsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CatalogsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Categories for Merchant ID with Items, Variations, and/or ModifierLists
         * @param {string} merchantId 
         * @param {GetCatalogActingAsEnum} actingAs 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {string} [locationId] 
         * @param {boolean} [items] 
         * @param {boolean} [images] 
         * @param {boolean} [variations] 
         * @param {boolean} [modifierLists] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCatalog(merchantId: string, actingAs: GetCatalogActingAsEnum, page?: number, limit?: number, locationId?: string, items?: boolean, images?: boolean, variations?: boolean, modifierLists?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CategoryPaginatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCatalog(merchantId, actingAs, page, limit, locationId, items, images, variations, modifierLists, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get Item with ID
         * @param {string} id 
         * @param {string} [locationId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getItem(id: string, locationId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Item>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getItem(id, locationId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get Items in Category
         * @param {string} id 
         * @param {GetItemsInCategoryActingAsEnum} [actingAs] 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {string} [locationId] 
         * @param {boolean} [images] 
         * @param {boolean} [variations] 
         * @param {boolean} [modifierLists] 
         * @param {string} [merchantId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getItemsInCategory(id: string, actingAs?: GetItemsInCategoryActingAsEnum, page?: number, limit?: number, locationId?: string, images?: boolean, variations?: boolean, modifierLists?: boolean, merchantId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ItemPaginatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getItemsInCategory(id, actingAs, page, limit, locationId, images, variations, modifierLists, merchantId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get your Categories with Items, Variations, and/or ModifierLists
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {string} [locationId] 
         * @param {boolean} [items] 
         * @param {boolean} [images] 
         * @param {boolean} [variations] 
         * @param {boolean} [modifierLists] 
         * @param {GetMyCatalogActingAsEnum} [actingAs] 
         * @param {string} [merchantId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyCatalog(page?: number, limit?: number, locationId?: string, items?: boolean, images?: boolean, variations?: boolean, modifierLists?: boolean, actingAs?: GetMyCatalogActingAsEnum, merchantId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CategoryPaginatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyCatalog(page, limit, locationId, items, images, variations, modifierLists, actingAs, merchantId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get Item variations with ID
         * @param {string} id 
         * @param {string} [locationId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVariationsForItem(id: string, locationId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Variation>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVariationsForItem(id, locationId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update multiple Categories
         * @param {Array<CategoryUpdateAllDto>} categoryUpdateAllDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCategories(categoryUpdateAllDto: Array<CategoryUpdateAllDto>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Category>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCategories(categoryUpdateAllDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update a Category
         * @param {string} id 
         * @param {CategoryUpdateDto} categoryUpdateDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCategory(id: string, categoryUpdateDto: CategoryUpdateDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Category>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCategory(id, categoryUpdateDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update an Item
         * @param {string} id 
         * @param {ItemUpdateDto} itemUpdateDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateItem(id: string, itemUpdateDto: ItemUpdateDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Item>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateItem(id, itemUpdateDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update multiple Items
         * @param {Array<ItemUpdateAllDto>} itemUpdateAllDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateItems(itemUpdateAllDto: Array<ItemUpdateAllDto>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Item>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateItems(itemUpdateAllDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update an Variation
         * @param {string} id 
         * @param {VariationUpdateDto} variationUpdateDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateVariation(id: string, variationUpdateDto: VariationUpdateDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Variation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateVariation(id, variationUpdateDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Upload Square Catalog Image
         * @param {string} idempotencyKey 
         * @param {string} id 
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadImageToSquareCatalog(idempotencyKey: string, id: string, file?: File, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CatalogImage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadImageToSquareCatalog(idempotencyKey, id, file, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CatalogsApi - factory interface
 * @export
 */
export const CatalogsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CatalogsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Categories for Merchant ID with Items, Variations, and/or ModifierLists
         * @param {CatalogsApiGetCatalogRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCatalog(requestParameters: CatalogsApiGetCatalogRequest, options?: AxiosRequestConfig): AxiosPromise<CategoryPaginatedResponse> {
            return localVarFp.getCatalog(requestParameters.merchantId, requestParameters.actingAs, requestParameters.page, requestParameters.limit, requestParameters.locationId, requestParameters.items, requestParameters.images, requestParameters.variations, requestParameters.modifierLists, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Item with ID
         * @param {CatalogsApiGetItemRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItem(requestParameters: CatalogsApiGetItemRequest, options?: AxiosRequestConfig): AxiosPromise<Item> {
            return localVarFp.getItem(requestParameters.id, requestParameters.locationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Items in Category
         * @param {CatalogsApiGetItemsInCategoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getItemsInCategory(requestParameters: CatalogsApiGetItemsInCategoryRequest, options?: AxiosRequestConfig): AxiosPromise<ItemPaginatedResponse> {
            return localVarFp.getItemsInCategory(requestParameters.id, requestParameters.actingAs, requestParameters.page, requestParameters.limit, requestParameters.locationId, requestParameters.images, requestParameters.variations, requestParameters.modifierLists, requestParameters.merchantId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get your Categories with Items, Variations, and/or ModifierLists
         * @param {CatalogsApiGetMyCatalogRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCatalog(requestParameters: CatalogsApiGetMyCatalogRequest = {}, options?: AxiosRequestConfig): AxiosPromise<CategoryPaginatedResponse> {
            return localVarFp.getMyCatalog(requestParameters.page, requestParameters.limit, requestParameters.locationId, requestParameters.items, requestParameters.images, requestParameters.variations, requestParameters.modifierLists, requestParameters.actingAs, requestParameters.merchantId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Item variations with ID
         * @param {CatalogsApiGetVariationsForItemRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVariationsForItem(requestParameters: CatalogsApiGetVariationsForItemRequest, options?: AxiosRequestConfig): AxiosPromise<Array<Variation>> {
            return localVarFp.getVariationsForItem(requestParameters.id, requestParameters.locationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update multiple Categories
         * @param {CatalogsApiUpdateCategoriesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCategories(requestParameters: CatalogsApiUpdateCategoriesRequest, options?: AxiosRequestConfig): AxiosPromise<Array<Category>> {
            return localVarFp.updateCategories(requestParameters.categoryUpdateAllDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a Category
         * @param {CatalogsApiUpdateCategoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCategory(requestParameters: CatalogsApiUpdateCategoryRequest, options?: AxiosRequestConfig): AxiosPromise<Category> {
            return localVarFp.updateCategory(requestParameters.id, requestParameters.categoryUpdateDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an Item
         * @param {CatalogsApiUpdateItemRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateItem(requestParameters: CatalogsApiUpdateItemRequest, options?: AxiosRequestConfig): AxiosPromise<Item> {
            return localVarFp.updateItem(requestParameters.id, requestParameters.itemUpdateDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update multiple Items
         * @param {CatalogsApiUpdateItemsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateItems(requestParameters: CatalogsApiUpdateItemsRequest, options?: AxiosRequestConfig): AxiosPromise<Array<Item>> {
            return localVarFp.updateItems(requestParameters.itemUpdateAllDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an Variation
         * @param {CatalogsApiUpdateVariationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVariation(requestParameters: CatalogsApiUpdateVariationRequest, options?: AxiosRequestConfig): AxiosPromise<Variation> {
            return localVarFp.updateVariation(requestParameters.id, requestParameters.variationUpdateDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload Square Catalog Image
         * @param {CatalogsApiUploadImageToSquareCatalogRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadImageToSquareCatalog(requestParameters: CatalogsApiUploadImageToSquareCatalogRequest, options?: AxiosRequestConfig): AxiosPromise<CatalogImage> {
            return localVarFp.uploadImageToSquareCatalog(requestParameters.idempotencyKey, requestParameters.id, requestParameters.file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getCatalog operation in CatalogsApi.
 * @export
 * @interface CatalogsApiGetCatalogRequest
 */
export interface CatalogsApiGetCatalogRequest {
    /**
     * 
     * @type {string}
     * @memberof CatalogsApiGetCatalog
     */
    readonly merchantId: string

    /**
     * 
     * @type {'merchant' | 'customer'}
     * @memberof CatalogsApiGetCatalog
     */
    readonly actingAs: GetCatalogActingAsEnum

    /**
     * 
     * @type {number}
     * @memberof CatalogsApiGetCatalog
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof CatalogsApiGetCatalog
     */
    readonly limit?: number

    /**
     * 
     * @type {string}
     * @memberof CatalogsApiGetCatalog
     */
    readonly locationId?: string

    /**
     * 
     * @type {boolean}
     * @memberof CatalogsApiGetCatalog
     */
    readonly items?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof CatalogsApiGetCatalog
     */
    readonly images?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof CatalogsApiGetCatalog
     */
    readonly variations?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof CatalogsApiGetCatalog
     */
    readonly modifierLists?: boolean
}

/**
 * Request parameters for getItem operation in CatalogsApi.
 * @export
 * @interface CatalogsApiGetItemRequest
 */
export interface CatalogsApiGetItemRequest {
    /**
     * 
     * @type {string}
     * @memberof CatalogsApiGetItem
     */
    readonly id: string

    /**
     * 
     * @type {string}
     * @memberof CatalogsApiGetItem
     */
    readonly locationId?: string
}

/**
 * Request parameters for getItemsInCategory operation in CatalogsApi.
 * @export
 * @interface CatalogsApiGetItemsInCategoryRequest
 */
export interface CatalogsApiGetItemsInCategoryRequest {
    /**
     * 
     * @type {string}
     * @memberof CatalogsApiGetItemsInCategory
     */
    readonly id: string

    /**
     * 
     * @type {'merchant' | 'customer'}
     * @memberof CatalogsApiGetItemsInCategory
     */
    readonly actingAs?: GetItemsInCategoryActingAsEnum

    /**
     * 
     * @type {number}
     * @memberof CatalogsApiGetItemsInCategory
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof CatalogsApiGetItemsInCategory
     */
    readonly limit?: number

    /**
     * 
     * @type {string}
     * @memberof CatalogsApiGetItemsInCategory
     */
    readonly locationId?: string

    /**
     * 
     * @type {boolean}
     * @memberof CatalogsApiGetItemsInCategory
     */
    readonly images?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof CatalogsApiGetItemsInCategory
     */
    readonly variations?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof CatalogsApiGetItemsInCategory
     */
    readonly modifierLists?: boolean

    /**
     * 
     * @type {string}
     * @memberof CatalogsApiGetItemsInCategory
     */
    readonly merchantId?: string
}

/**
 * Request parameters for getMyCatalog operation in CatalogsApi.
 * @export
 * @interface CatalogsApiGetMyCatalogRequest
 */
export interface CatalogsApiGetMyCatalogRequest {
    /**
     * 
     * @type {number}
     * @memberof CatalogsApiGetMyCatalog
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof CatalogsApiGetMyCatalog
     */
    readonly limit?: number

    /**
     * 
     * @type {string}
     * @memberof CatalogsApiGetMyCatalog
     */
    readonly locationId?: string

    /**
     * 
     * @type {boolean}
     * @memberof CatalogsApiGetMyCatalog
     */
    readonly items?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof CatalogsApiGetMyCatalog
     */
    readonly images?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof CatalogsApiGetMyCatalog
     */
    readonly variations?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof CatalogsApiGetMyCatalog
     */
    readonly modifierLists?: boolean

    /**
     * 
     * @type {'merchant' | 'customer'}
     * @memberof CatalogsApiGetMyCatalog
     */
    readonly actingAs?: GetMyCatalogActingAsEnum

    /**
     * 
     * @type {string}
     * @memberof CatalogsApiGetMyCatalog
     */
    readonly merchantId?: string
}

/**
 * Request parameters for getVariationsForItem operation in CatalogsApi.
 * @export
 * @interface CatalogsApiGetVariationsForItemRequest
 */
export interface CatalogsApiGetVariationsForItemRequest {
    /**
     * 
     * @type {string}
     * @memberof CatalogsApiGetVariationsForItem
     */
    readonly id: string

    /**
     * 
     * @type {string}
     * @memberof CatalogsApiGetVariationsForItem
     */
    readonly locationId?: string
}

/**
 * Request parameters for updateCategories operation in CatalogsApi.
 * @export
 * @interface CatalogsApiUpdateCategoriesRequest
 */
export interface CatalogsApiUpdateCategoriesRequest {
    /**
     * 
     * @type {Array<CategoryUpdateAllDto>}
     * @memberof CatalogsApiUpdateCategories
     */
    readonly categoryUpdateAllDto: Array<CategoryUpdateAllDto>
}

/**
 * Request parameters for updateCategory operation in CatalogsApi.
 * @export
 * @interface CatalogsApiUpdateCategoryRequest
 */
export interface CatalogsApiUpdateCategoryRequest {
    /**
     * 
     * @type {string}
     * @memberof CatalogsApiUpdateCategory
     */
    readonly id: string

    /**
     * 
     * @type {CategoryUpdateDto}
     * @memberof CatalogsApiUpdateCategory
     */
    readonly categoryUpdateDto: CategoryUpdateDto
}

/**
 * Request parameters for updateItem operation in CatalogsApi.
 * @export
 * @interface CatalogsApiUpdateItemRequest
 */
export interface CatalogsApiUpdateItemRequest {
    /**
     * 
     * @type {string}
     * @memberof CatalogsApiUpdateItem
     */
    readonly id: string

    /**
     * 
     * @type {ItemUpdateDto}
     * @memberof CatalogsApiUpdateItem
     */
    readonly itemUpdateDto: ItemUpdateDto
}

/**
 * Request parameters for updateItems operation in CatalogsApi.
 * @export
 * @interface CatalogsApiUpdateItemsRequest
 */
export interface CatalogsApiUpdateItemsRequest {
    /**
     * 
     * @type {Array<ItemUpdateAllDto>}
     * @memberof CatalogsApiUpdateItems
     */
    readonly itemUpdateAllDto: Array<ItemUpdateAllDto>
}

/**
 * Request parameters for updateVariation operation in CatalogsApi.
 * @export
 * @interface CatalogsApiUpdateVariationRequest
 */
export interface CatalogsApiUpdateVariationRequest {
    /**
     * 
     * @type {string}
     * @memberof CatalogsApiUpdateVariation
     */
    readonly id: string

    /**
     * 
     * @type {VariationUpdateDto}
     * @memberof CatalogsApiUpdateVariation
     */
    readonly variationUpdateDto: VariationUpdateDto
}

/**
 * Request parameters for uploadImageToSquareCatalog operation in CatalogsApi.
 * @export
 * @interface CatalogsApiUploadImageToSquareCatalogRequest
 */
export interface CatalogsApiUploadImageToSquareCatalogRequest {
    /**
     * 
     * @type {string}
     * @memberof CatalogsApiUploadImageToSquareCatalog
     */
    readonly idempotencyKey: string

    /**
     * 
     * @type {string}
     * @memberof CatalogsApiUploadImageToSquareCatalog
     */
    readonly id: string

    /**
     * 
     * @type {File}
     * @memberof CatalogsApiUploadImageToSquareCatalog
     */
    readonly file?: File
}

/**
 * CatalogsApi - object-oriented interface
 * @export
 * @class CatalogsApi
 * @extends {BaseAPI}
 */
export class CatalogsApi extends BaseAPI {
    /**
     * 
     * @summary Get Categories for Merchant ID with Items, Variations, and/or ModifierLists
     * @param {CatalogsApiGetCatalogRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogsApi
     */
    public getCatalog(requestParameters: CatalogsApiGetCatalogRequest, options?: AxiosRequestConfig) {
        return CatalogsApiFp(this.configuration).getCatalog(requestParameters.merchantId, requestParameters.actingAs, requestParameters.page, requestParameters.limit, requestParameters.locationId, requestParameters.items, requestParameters.images, requestParameters.variations, requestParameters.modifierLists, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Item with ID
     * @param {CatalogsApiGetItemRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogsApi
     */
    public getItem(requestParameters: CatalogsApiGetItemRequest, options?: AxiosRequestConfig) {
        return CatalogsApiFp(this.configuration).getItem(requestParameters.id, requestParameters.locationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Items in Category
     * @param {CatalogsApiGetItemsInCategoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogsApi
     */
    public getItemsInCategory(requestParameters: CatalogsApiGetItemsInCategoryRequest, options?: AxiosRequestConfig) {
        return CatalogsApiFp(this.configuration).getItemsInCategory(requestParameters.id, requestParameters.actingAs, requestParameters.page, requestParameters.limit, requestParameters.locationId, requestParameters.images, requestParameters.variations, requestParameters.modifierLists, requestParameters.merchantId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get your Categories with Items, Variations, and/or ModifierLists
     * @param {CatalogsApiGetMyCatalogRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogsApi
     */
    public getMyCatalog(requestParameters: CatalogsApiGetMyCatalogRequest = {}, options?: AxiosRequestConfig) {
        return CatalogsApiFp(this.configuration).getMyCatalog(requestParameters.page, requestParameters.limit, requestParameters.locationId, requestParameters.items, requestParameters.images, requestParameters.variations, requestParameters.modifierLists, requestParameters.actingAs, requestParameters.merchantId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Item variations with ID
     * @param {CatalogsApiGetVariationsForItemRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogsApi
     */
    public getVariationsForItem(requestParameters: CatalogsApiGetVariationsForItemRequest, options?: AxiosRequestConfig) {
        return CatalogsApiFp(this.configuration).getVariationsForItem(requestParameters.id, requestParameters.locationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update multiple Categories
     * @param {CatalogsApiUpdateCategoriesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogsApi
     */
    public updateCategories(requestParameters: CatalogsApiUpdateCategoriesRequest, options?: AxiosRequestConfig) {
        return CatalogsApiFp(this.configuration).updateCategories(requestParameters.categoryUpdateAllDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a Category
     * @param {CatalogsApiUpdateCategoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogsApi
     */
    public updateCategory(requestParameters: CatalogsApiUpdateCategoryRequest, options?: AxiosRequestConfig) {
        return CatalogsApiFp(this.configuration).updateCategory(requestParameters.id, requestParameters.categoryUpdateDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an Item
     * @param {CatalogsApiUpdateItemRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogsApi
     */
    public updateItem(requestParameters: CatalogsApiUpdateItemRequest, options?: AxiosRequestConfig) {
        return CatalogsApiFp(this.configuration).updateItem(requestParameters.id, requestParameters.itemUpdateDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update multiple Items
     * @param {CatalogsApiUpdateItemsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogsApi
     */
    public updateItems(requestParameters: CatalogsApiUpdateItemsRequest, options?: AxiosRequestConfig) {
        return CatalogsApiFp(this.configuration).updateItems(requestParameters.itemUpdateAllDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an Variation
     * @param {CatalogsApiUpdateVariationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogsApi
     */
    public updateVariation(requestParameters: CatalogsApiUpdateVariationRequest, options?: AxiosRequestConfig) {
        return CatalogsApiFp(this.configuration).updateVariation(requestParameters.id, requestParameters.variationUpdateDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload Square Catalog Image
     * @param {CatalogsApiUploadImageToSquareCatalogRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogsApi
     */
    public uploadImageToSquareCatalog(requestParameters: CatalogsApiUploadImageToSquareCatalogRequest, options?: AxiosRequestConfig) {
        return CatalogsApiFp(this.configuration).uploadImageToSquareCatalog(requestParameters.idempotencyKey, requestParameters.id, requestParameters.file, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetCatalogActingAsEnum = {
    Merchant: 'merchant',
    Customer: 'customer'
} as const;
export type GetCatalogActingAsEnum = typeof GetCatalogActingAsEnum[keyof typeof GetCatalogActingAsEnum];
/**
 * @export
 */
export const GetItemsInCategoryActingAsEnum = {
    Merchant: 'merchant',
    Customer: 'customer'
} as const;
export type GetItemsInCategoryActingAsEnum = typeof GetItemsInCategoryActingAsEnum[keyof typeof GetItemsInCategoryActingAsEnum];
/**
 * @export
 */
export const GetMyCatalogActingAsEnum = {
    Merchant: 'merchant',
    Customer: 'customer'
} as const;
export type GetMyCatalogActingAsEnum = typeof GetMyCatalogActingAsEnum[keyof typeof GetMyCatalogActingAsEnum];
